### PR TITLE
pre-commit: introduce pre-commit hooks

### PR DESCRIPTION
**Pull request by schuellerf**
those check for eol, yaml syntax and similar

adding pytest is probably too slow and annoying... let's see

### CODE REVIEW

**Comment by supakeen** [comment]
@schuellerf Could we re-use the current `make` commands (`lint`, `test`, `type`) at least partially (I know `type` is failing atm)?

**Comment by schuellerf** [comment]
pre-commit is different as it hooks into "git commit"
That's somehow different and I'd rather target to cover the basic github actions here to avoid roundtrips in PR-pushes

**Comment by mvo5** [comment]
> @schuellerf Could we re-use the current `make` commands (`lint`, `test`, `type`) at least partially (I know `type` is failing atm)?

I agree here, it seems nice to have a single "make" or "make check" to run all checks (or is pre-commit maybe super common and I'm just not up-to-date?).

**Comment by schuellerf** [comment]
It would just be an easy option to include it into the git workflow and not to forget the small things before committing.
still "make check" could run "pre-commit run --all-files" _and_ include the more extensive pytests

**Comment by supakeen** [comment]
I'd be happy to merge this; we can iterate on it later as it's purely local developer experience. Can you add `pre-commit` to the dev dependency extras? :)

**Comment by schuellerf** [comment]
> I'd be happy to merge this; we can iterate on it later as it's purely local developer experience. Can you add `pre-commit` to the dev dependency extras? :)

… totally makes sense - sorry :-D

**Review by supakeen — APPROVED** [review]

**Pull request merged**
