### PR TITLE
example/centos: deduplication of package sets

### PR DESCRIPTION
**Pull request by supakeen**
This PR has ongoing work in deduplicating and sharing things regarding package sets. It is draft because more can/should be done.

### CODE REVIEW

**Comment by supakeen** [comment]
There isn't *much* more to be gained in this PR regarding `+/-` lines. I'm already on the fence on further deduplication. Let's merge it as is (?) and followup with more as it makes sense.

**Review by schuellerf — APPROVED** [review]
lgtm, as the tests are good, it looks shorter and well structured, it's am improvement :-D

**Comment by supakeen** [comment]
Needs rebase after I land the rename-externals-PR here.

**Review by mvo5 — COMMENTED** [review]
Quick high level feedback, I would call _include.ymal just "common.yaml" (or _common.yaml") (that is what the includes are, yes?), seems slightly more descriptive.

another one might be:
```yaml
diff --git a/example/centos/centos-9-x86_64-qcow2.yaml b/example/centos/centos-9-x86_64-qcow2.yaml
index b1636ab..05e9fd3 100644
--- a/example/centos/centos-9-x86_64-qcow2.yaml
+++ b/example/centos/centos-9-x86_64-qcow2.yaml
@@ -17,7 +17,11 @@ otk.define:
         repositories:
           otk.include: "common/repositories/${architecture}.yaml"
         packages:
-          otk.include: "common/package-set/${architecture}/build/qcow2_vmdk.yaml"
+          otk.op.join:
+            - otk.include: "common/package-set/${architecture}/build/_include.yaml"
+            - - dosfstools
+              - qemu-img
+              - xfsprogs
     os:
       otk.external.osbuild-gen-depsolve-dnf4:
         architecture: ${architecture}
```
i.e. make things less indirect and include the (small) package differences directly in the top-level (no strong opinion here).

And finally how much overlap is between arches? I.e. would it make sense to have  a common arch-indepentant set, as a random data point:
````
$ diff -u common/package-set/aarch64/os/ami.yaml common/package-set/x86_64/os/ami.yaml
--- common/package-set/aarch64/os/ami.yaml	2024-10-07 15:09:17.429634518 +0200
+++ common/package-set/x86_64/os/ami.yaml	2024-10-07 15:09:17.429634518 +0200
@@ -13,6 +13,7 @@
         - dhcp-client
         - gdisk
         - grub2
+        - grub2-pc
         - langpacks-en
         - redhat-release
         - redhat-release-eula
@@ -23,8 +24,8 @@
         - yum-utils
 exclude:
   - aic94xx-firmware
-  - alsa-lib
   - alsa-firmware
+  - alsa-lib
   - alsa-tools-firmware
   - biosdevname
   - firewalld
```
the two arches look extremly similar and qcow2 has also only a single package as difference.

**Comment by supakeen** [comment]
@mvo5 Agreed on the rename of `_include.yaml`. I'll call them common. My initial thinking was that `_` prefixed files should never be included directly :)

**Comment by supakeen** [comment]
As for the sharing of more things, yes I think that's a good idea for a followup, I consider this one to be a starting point for *more* deduplication as we see fit.

Perhaps even after we reconsider (some of) the package sets as they currently live in images.

**Comment by mvo5** [comment]
> @mvo5 Agreed on the rename of `_include.yaml`. I'll call them common. My initial thinking was that `_` prefixed files should never be included directly :)

I don't mind  `_common.yaml`, no strong opinion here.

**Comment by supakeen** [comment]
Updated name to `common.yaml`; rebased on now-working-tests after the rename :)

**Review by mvo5 — APPROVED** [review]

**Pull request merged**
