### PR TITLE
CI: Add examples building for each PR / push

### PR DESCRIPTION
**Pull request by elkoniu**
OTK repo contains examples which can be used by users. This PR adds CI routine to be sure they are build each time without any errors.

Resolves: https://github.com/osbuild/otk/issues/65

### CODE REVIEW

**Comment by supakeen** [comment]
Feel free to fix up the `Self` import, I was unaware that this was such a recent addition to Python.

**Comment by bcl** [comment]
Do we need to test 3.8? RHEL9 has python 3.9, and Fedora 39 and 40 are on python3.12 so we should probably test every version in-between 3.9 and 3.12

**Comment by elkoniu** [comment]
> Feel free to fix up the `Self` import, I was unaware that this was such a recent addition to Python.

Can you elaborate on this a bit more? Which `self` import do you mean?

**Comment by elkoniu** [comment]
> Do we need to test 3.8? RHEL9 has python 3.9, and Fedora 39 and 40 are on python3.12 so we should probably test every version in-between 3.9 and 3.12

I think we could skip 3.8 but it is up to @supakeen decision :)

**Comment by supakeen** [comment]
@elkoniu 3.9 and up only.

**Comment by supakeen** [comment]
This is now done through image references.

**Pull request closed without merging**
