### PR TITLE
make: move pre-commit to lint step

### PR DESCRIPTION
**Pull request by supakeen**
pre-commit is mostly doing linting thingies.

### CODE REVIEW

**Comment by supakeen** [comment]
For some reason this is doing weird things (I think it's not recognizing the `pyproject.toml` or it's in the 'wrong' directory?).

**Comment by schuellerf** [comment]
As pre-commit is very fast I'd maybe make a separate rule and call it from lint _and_ test?

**Comment by supakeen** [comment]
@schuellerf Agreed, I've added a commit that does this and I'll update #29.

**Review by schuellerf — APPROVED** [review]

**Comment by supakeen** [comment]
Closing in favor of a new PR, this got messy.

**Pull request closed without merging**
