### PR TITLE
many: add `pylint` to linters and fix warnings

### PR DESCRIPTION
**Pull request by mvo5**
This commit adds pylint and fixes the various warnings that it triggers. There are still some disabled ones left but this captures many of the low-hanging fruits.

### CODE REVIEW

**Review by supakeen — CHANGES_REQUESTED** [review]
Let's add `pylint` to `pre-commit` instead of making it a separate test, or is it too slow?

**Comment by mvo5** [comment]
> Let's add `pylint` to `pre-commit` instead of making it a separate test, or is it too slow?

It is fairly slow, idk what people find tolerable if noone else minds I can move it into pre-commit.

**Comment by supakeen** [comment]
> > Let's add `pylint` to `pre-commit` instead of making it a separate test, or is it too slow?
> 
> It is fairly slow, idk what people find tolerable if noone else minds I can move it into pre-commit.

I'd mind because I don't want people to turn off pre-commit; let's keep it separate if it's a noticeable delay.

**Review by supakeen — DISMISSED** [review]

**Comment by mvo5** [comment]
> > > Let's add `pylint` to `pre-commit` instead of making it a separate test, or is it too slow?
> > 
> > 
> > It is fairly slow, idk what people find tolerable if noone else minds I can move it into pre-commit.
> 
> I'd mind because I don't want people to turn off pre-commit; let's keep it separate if it's a noticeable delay.

It's 2.9s with pylint vs 0.75s without pylint on my system. I made it a separate commit, happy to revert it again :)

**Review by supakeen — DISMISSED** [review]

**Comment by mvo5** [comment]
Sorry, had to force push (a couple of times) to get the "lint.yml" gh changes right. But I do hope it's good now :)

**Review by supakeen — APPROVED** [review]

**Pull request merged**
